export const parentCategorySlugs = {
  groups: 'groups',
  channels: 'channels',
  videos: 'videos',
  chat: 'chat',
} as const;

export const subcategorySlugs = {
  pornhub: 'pornhub',
  porn: 'porn',
  sex: 'sex',
  nude: 'nudes',
  NSFW: 'nsfw',
  hot: 'hot',
  amateur: 'amateur',
  masturbation: 'masturbation',
  bitches: 'bitches',
  big_dick: 'big-dick',
  big_tits: 'big-tits',
  big_ass: 'big-ass',
  curvy: 'curvy',
  gay: 'gay',
  trans: 'trans',
  shemale: 'shemale',
  twink: 'twink',
  ladyboy: 'ladyboy',
  BDSM: 'bdsm',
  hentai: 'hentai',
  gangbang: 'gangbang',
  kink: 'kink',
  femdom: 'femdom',
  anal: 'anal',
  voyeur: 'voyeur',
  swinger: 'swinger',
  blowjob: 'blowjob',
  threesome: 'threesome',
  public: 'public',
  webcam: 'webcam',
  hardcore: 'hardcore',
  bukkake: 'bukkake',
  feet: 'feet',
  extreme: 'extreme',
  dark_porn: 'dark-porn',
  MILF: 'milf',
  cougar: 'cougar',
  mature: 'mature',
  teen: 'teen',
  students: 'students',
  stepmom: 'stepmom',
  OnlyFans: 'onlyfans',
  escorts: 'escorts',
  Latina: 'latina',
  Asian: 'asian',
  Arab: 'arab',
  Indian: 'indian',
  cuckold: 'cuckold',
  squirting: 'squirting',
  cosplay: 'cosplay',
} as const;

// It might also be useful to export the keys for type safety elsewhere
export type ParentCategoryKey = keyof typeof parentCategorySlugs;
export type SubcategoryKey = keyof typeof subcategorySlugs; 